apiVersion: v1
kind: Secret
metadata:
  name: assurance-service-secret
  namespace: neuroguard
type: Opaque
stringData:
  # Database
  SPRING_DATASOURCE_PASSWORD: ""
  JWT_SECRET: "XDkzF2YNPA/7vXmPYJmaACjY6VBhwHJbr4pzPF5jguE="
  # Email (Gmail)
  MAIL_USERNAME: "your-email@gmail.com"
  MAIL_PASSWORD: "your-app-password"
  # Twilio SMS
  TWILIO_ACCOUNT_SID: "your-twilio-account-sid"
  TWILIO_AUTH_TOKEN: "your-twilio-auth-token"
  TWILIO_PHONE_NUMBER: "+1234567890"
