apiVersion: v1
kind: Service
metadata:
  name: prescription-service
  namespace: neuroguard
  labels:
    app: prescription-service
spec:
  selector:
    app: prescription-service
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
  type: LoadBalancer
