apiVersion: v1
kind: Secret
metadata:
  name: medical-history-service-secret
  namespace: neuroguard
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "root"
  JWT_SECRET: "XDkzF2YNPA/7vXmPYJmaACjY6VBhwHJbr4pzPF5jguE="
