apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: neuroguard
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlzcWxwYXNz   # base64 encoded value
  MYSQL_USER: bXl1c2Vy
  MYSQL_PASSWORD: bXlwYXNz