apiVersion: v1
kind: Service
metadata:
  name: risk-alert-service
  namespace: neuroguard
  labels:
    app: risk-alert-service
spec:
  selector:
    app: risk-alert-service
  ports:
    - name: http
      protocol: TCP
      port: 8092
      targetPort: 8092
      nodePort: 30092
  type: NodePort
