apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultation-service
  namespace: neuroguard
  labels:
    app: consultation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultation-service
  template:
    metadata:
      labels:
        app: consultation-service
    spec:
      containers:
        - name: consultation-service
          image: YOUR_DOCKERHUB_USER/consultation-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: consultation-service-config
            - secretRef:
                name: consultation-service-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 6
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
