apiVersion: v1
kind: Secret
metadata:
  name: consultation-service-secret
  namespace: neuroguard
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: ""
  JWT_SECRET: "XDkzF2YNPA/7vXmPYJmaACjY6VBhwHJbr4pzPF5jguE="
  APP_DISTANCE_MATRIX_GOOGLE_API_KEY: "YOUR_GOOGLE_MAPS_API_KEY"
