pipeline {
    agent any

    triggers {
        pollSCM('H/5 * * * *')
    }

    environment {
        GIT_REPO       = 'https://github.com/saifeddinefrikhi-lab/Esprit-PIDEV-4SAE8-2526-NeuroGuard.git'
        GIT_BRANCH     = 'main' 
        SONAR_TOKEN    = credentials('sonar-token')
        SONAR_HOST_URL = credentials('http://192.168.158.240:9000')
        DOCKER_IMAGE   = "neuroguard/forums-service"
        DOCKER_TAG     = "${env.BUILD_NUMBER}"
        SERVICE_DIR    = "neuroguard-backend/forums-service"
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    stages {

        stage('Code Checkout') {
            steps {
                git branch: "${GIT_BRANCH}",
                    url: "${GIT_REPO}"
            }
        }

        stage('Build & JUnit Tests') {
            steps {
                dir("${SERVICE_DIR}") {
                    sh '''
                        mvn clean verify -B \
                            -Dspring.datasource.url=jdbc:h2:mem:testdb \
                            -Dspring.datasource.driver-class-name=org.h2.Driver \
                            -Dspring.jpa.database-platform=org.hibernate.dialect.H2Dialect
                    '''
                }
            }
            post {
                always {
                    junit "${SERVICE_DIR}/target/surefire-reports/*.xml"
                    jacoco(
                        execPattern:   "${SERVICE_DIR}/target/jacoco.exec",
                        classPattern:  "${SERVICE_DIR}/target/classes",
                        sourcePattern: "${SERVICE_DIR}/src/main/java"
                    )
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir("${SERVICE_DIR}") {
                    withSonarQubeEnv('SonarQube') {
                        sh '''
                            mvn sonar:sonar -B \
                                -Dsonar.projectKey=neuroguard-forums-service \
                                -Dsonar.projectName="NeuroGuard - Forums Service" \
                                -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
                        '''
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${SERVICE_DIR}") {
                    sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -t ${DOCKER_IMAGE}:latest ."
                }
            }
        }
    }

    post {
        always { cleanWs() }
    }
}
