apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: neuroguard
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: NodePort
