pipeline {
    agent any
    triggers {
        pollSCM('H/5 * * * *')
    }
    environment {
        GIT_REPO     = 'https://github.com/saifeddinefrikhi-lab/Esprit-PIDEV-4SAE8-2526-NeuroGuard.git'
        GIT_BRANCH   = 'main'
        SONAR_TOKEN  = credentials('sonar-token')
        DOCKER_IMAGE = "neuroguard/user-service"
        DOCKER_TAG   = "${env.BUILD_NUMBER}"
        SERVICE_DIR  = "neuroguard-backend/user-service"
        MAVEN_OPTS   = "-Xmx1024m -XX:MaxPermSize=512m"
    }
    options { timeout(time: 30, unit: 'MINUTES'); disableConcurrentBuilds() }
    stages {
        stage('Code Checkout') {
            steps {
                git branch: "${GIT_BRANCH}",
                    url: "${GIT_REPO}"
            }
        }
        stage('JUnit Tests') {
            steps {
                dir("${SERVICE_DIR}") {
                    sh "mvn clean test -B"
                }
            }
        }
        stage('Build ') {
            steps {
                dir("${SERVICE_DIR}") {
                    sh "mvn clean package -DskipTests"
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
                dir("${SERVICE_DIR}") {
                    withSonarQubeEnv('SonarQube') {
                        sh 'mvn sonar:sonar -B -Dsonar.projectKey=neuroguard-user-service -Dsonar.projectName="NeuroGuard - User Service" -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml'
                    }
                }
            }
        }
        stage('Quality Gate') {
            steps { timeout(time: 5, unit: 'MINUTES') { waitForQualityGate abortPipeline: true } }
        }
        stage('Build Docker Image') {
            steps { dir("${SERVICE_DIR}") { sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -t ${DOCKER_IMAGE}:latest ." } }
        }
    }
    post { always { cleanWs() } }
}