apiVersion: v1
kind: Service
metadata:
  name: pharmacy-service
  namespace: neuroguard
  labels:
    app: pharmacy-service
spec:
  selector:
    app: pharmacy-service
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  type: LoadBalancer
